#!/usr/bin/env bash

[[ $_ == $0 ]] && echo "Please source me!" && exit 1

: ${DOTFILES_REPO=https://github.com/kaben/dotfiles.git}
: ${DOTFILES_DIR=${HOME}/.local/etc}
: ${DOTS_CLONE_DIR=${DOTFILES_DIR}}
: ${DOTS_REPO=https://github.com/kaben/dots.git}
: ${DOTS_DIR=${HOME}/.local/lib/dots}

# Clone or update dots repository
if [ -d "${DOTS_DIR}" ]; then
  cd ${DOTS_DIR}
  git pull origin master
else
  git clone ${DOTS_REPO} "${DOTS_DIR}"
fi

# Clone or update dotfiles repository
if [ -d "${DOTFILES_DIR}" ]; then
  cd ${DOTFILES_DIR}
  git pull origin master
else
  git clone ${DOTFILES_REPO} "${DOTFILES_DIR}"
  cd ${DOTFILES_DIR}
fi

# Bootstrap dots
source "${DOTS_DIR}/contrib/initialize"
